apiVersion: v1
kind: Service
metadata:
  name: clust-service

spec:
  type: clusterIP
  ports:
    targetPort: 80 #port on which backend (pods) are exposed
    port: 80 #service object port
    #node port is not required
  
  selector:
    app: nginx
    tier: frontend
