apiVersion: v1
kind: Service
metadata:
  name: myapp-serviced

spec:
  type: NodePort #ClusterIP, LoadBalancer
  ports:
    - targetPort: 8080
      nodePort: 30004
      port: 80
  selector:
    app: nginx-pod
    tier: frontend
    