#kubectl create -f compute-quota.yml
apiVersion: v1
kind: ResourceQuota #for limiting resources per namespace
metadata:
  name: compute-quota
  namespace: dev

spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    