apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: #Label can have any properties under it, can be named anything
    app: nginx
    tier: frontend

spec:
  containers: #list/ array because one pod can have multiple containers under it
    - image: nginx
      name: nginx